; ============================================================
; PlatformIO Configuration — Estufa Inteligente de Alface
; ESP32 DevKit V1 | 100% Offline | TinyML Ready
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; --- Serial Monitor ---
monitor_speed = 115200
monitor_port = COM15
upload_port = COM15

; --- Dependências ---
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; --- Otimizações de Memória ---
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections

; --- Linker: remover código morto ---
board_build.partitions = min_spiffs.csv
